// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSource(arg1:string):Promise<main.DesktopState>;

export function ChooseDirectory():Promise<string>;

export function CopyAddress(arg1:string):Promise<void>;

export function ExportConfig():Promise<void>;

export function GetState():Promise<main.DesktopState>;

export function ImportConfig():Promise<main.DesktopState>;

export function OpenBrowser(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RemoveSource(arg1:number):Promise<main.DesktopState>;

export function RestartSharing():Promise<main.DesktopState>;

export function SetLaunchAtStartup(arg1:boolean):Promise<main.DesktopState>;

export function SetPort(arg1:number):Promise<main.DesktopState>;

export function ShowWindow():Promise<void>;

export function StartSharing():Promise<main.DesktopState>;

export function StopSharing():Promise<main.DesktopState>;

export function UpdatePreferences(arg1:boolean,arg2:boolean):Promise<main.DesktopState>;

export function UpdateSource(arg1:number,arg2:string,arg3:string):Promise<main.DesktopState>;
