// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1) {
  return window['go']['main']['App']['AddSource'](arg1);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function CopyAddress(arg1) {
  return window['go']['main']['App']['CopyAddress'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function RestartSharing() {
  return window['go']['main']['App']['RestartSharing']();
}

export function SetLaunchAtStartup(arg1) {
  return window['go']['main']['App']['SetLaunchAtStartup'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartSharing() {
  return window['go']['main']['App']['StartSharing']();
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}

export function UpdatePreferences(arg1, arg2) {
  return window['go']['main']['App']['UpdatePreferences'](arg1, arg2);
}

export function UpdateSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSource'](arg1, arg2, arg3);
}
